### ISSUE TITLE
License information in `docker build`

### ISSUE THREAD

**Issue by mizuhirosuzuki** [AEADataEditor/docker-stata#16]
This might be a silly question, but do we need to pass the license information [here](https://github.com/AEADataEditor/docker-stata/blob/720f7370e8971d42087c7daf9ecba9ed268de4a3/README.md?plain=1#L52)?
Not sure how this information is used in the build process.

Thank you!

**Comment by larsvilhuber** [comment]
It is a remnant from wanting to run stata during the build process to, for instance, install Stata packages. You do not want to include, then remove the Stata license, since that would still embed the license in a layer. I erroneously did that initially, and had to delete a few Stata images. It is somewhat tricky to do that right. You do not need it. (I will remove it, in fact)
