### ISSUE TITLE
Allow to initialize stata.lic using environment variables

### ISSUE THREAD

**Issue by olivierdalang** [AEADataEditor/docker-stata#5]
Hi ! Thanks for the images !!

It would be nice if it was possible to initialize stata.lic using env vars (serial number, code and authorization).

This way one could easily use the image, without having to juggle with generating the license then having the mount the files, which is not easy to get right.

Cheers !

**Comment by larsvilhuber** [comment]
Agreed that this is useful, and that's how it is done in [labordynamicsinstitute/continuous-integration-stata](https://github.com/labordynamicsinstitute/continuous-integration-stata), based on @ledwindra 's work. An alternative, which is used in [labordynamicsinstitute/codespaces-stata-skeleton](https://github.com/labordynamicsinstitute/codespaces-stata-skeleton), is to encode the contents of the license file into a single encoded environment variable. 

I'll keep this open, since it makes sense to use an either/or approach to the entry-point script.

**Comment by larsvilhuber** [comment]
@olivierdalang I am this as "needs-help", because after having used this in various scenarios, the problem is that the stata license would need to be created within the docker by "root" user, and for security reasons, I am running everything inside the docker as a non-root user. While that could be done with judicious use of "sudo", I don't have time to debug that. 

I'll note that there is no need to generate the license, only mount it. In all cases, you presumably have the license because you have a legit version of Stata, and that means you have an existing license file.
