### ISSUE TITLE
Reduce image size

### ISSUE THREAD

**Issue by olivierdalang** [AEADataEditor/docker-stata#6]
The current images are around 1.25gb.

They could probably be made much lighter if using more docker-friendly base images such as debian-slim.
Didn't test yet, but I guess it would not require many changes in the Dockerfile.

That would make a big difference in making initial installs fasters, esp. useful in context with bad connectivity or on repeated calls (e.g. CI or other type of automated workflows)

**Comment by larsvilhuber** [comment]
@olivierdalang  I'm going to leave this closed since I doubt that it would gain much (but happy to be told otherwise). Stata binaries have lots of binaries, and usually, the processing is not limited to a single core Stata. But you could give it a try by using the two-stage build process (use debian slim, and then copy the Stata install from this one).
