### ISSUE TITLE
xstata-mp: error while loading shared libraries: libgthread-2.0.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by sscien** [AEADataEditor/docker-stata#8]
Hi,

I was trying to use xstata, but libgthread-2.0.so.0 is missing. Could you let me know how to add this library to the docker image? 

Thanks a lot.
EJ

**Comment by larsvilhuber** [comment]
`xstata` is not supported at this point, since there is no graphical interface provided either. While you *could* possibly do this with a local X server and starting Docker in a certain way, that's beyond the scope of this example. Use `stata` or `stata-mp` instead.

That being said, if you wanted to explore how to do this, have a look at [instructions to use the base Docker image for your projects](https://github.com/AEADataEditor/docker-stata#using-the-container-to-build-a-project-specific-docker-image). Conceptually, you will need to figure out all the missing libraries (I doubt that `libgthread` is the only one missing), and add them to the Docker file:
```
RUN apt-get install -y libgthread
```
(see also the relevant - more complex - lines in the original [Dockerfile](https://github.com/AEADataEditor/docker-stata/blob/d7f8d7dbd284a5a1ce1eb18d76bdcc2254f607ae/Dockerfile#L15))
